CREATE TABLE sala (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	disponibilidade boolean NOT NULL,
	qtd_assento INTEGER(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE sessao (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	filme BIGINT(20) NOT NULL,
	sala BIGINT(20) NOT NULL,
	date_time datetime NOT NULL,
	FOREIGN KEY (sala) REFERENCES sala(id),
    FOREIGN KEY (filme) REFERENCES filme(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE cat_ingresso (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	categoria VARCHAR(50) NOT NULL,
	valor DECIMAL(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE ingresso (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	sessao BIGINT(20) NOT NULL,
	cat_ingresso BIGINT(20) NOT NULL,
	FOREIGN KEY (sessao) REFERENCES sessao(id),
	FOREIGN KEY (cat_ingresso) REFERENCES cat_ingresso(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;